- name: "bug"
  color: "d73a4a"
  description: "Indicates an unexpected problem or unintended behavior"

- name: "feature request"
  color: "a2eeef"
  description: "New feature or improvement to existing functionalities"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "enhancement"
  color: "a2eeef"
  description: "Enhancement to an existing feature"

- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "high priority"
  color: "b60205"
  description: "Urgent attention is needed"

- name: "low priority"
  color: "0e8a16"
  description: "Lower impact, can be delayed"

- name: "in progress"
  color: "bfdadc"
  description: "Work is currently ongoing"

- name: "needs review"
  color: "fad8c7"
  description: "Pending review from maintainers"

- name: "backend"
  color: "d4c5f9"
  description: "Related to backend logic or server-side"

- name: "frontend"
  color: "fad8c1"
  description: "Related to front-end, such as UI improvements"

- name: "UI/UX"
  color: "fef2c0"
  description: "Issues addressing user interface and user experience"
