# .github/release-drafter.yml
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '"'
categories:
  - title: '🚀 Features'
    labels:
      - feature
  - title: '🐛 Bug Fixes'
    labels:
      - bug
template: |
  ## What’s Changed
  $CHANGES

  ## New Contributors
  $CONTRIBUTORS
