"""Minimal agentic tool-calling loop on top of ``TextAI``.

This module provides a synchronous, lightweight agent loop that drives OpenAI-style
Chat Completions with tools. It repeatedly calls ``TextAI.text_chat``, executes any
requested tools locally, and feeds results back into the conversation until the
model produces a final answer or a safeguard trips.

Example:
    from ai_backend.agent_loop import ToolRegistry, run_agentic_chat
    from ai_backend.api import TextAI

    def add(a: int, b: int) -> int:
        return a + b

    tools = [
        {
            "type": "function",
            "function": {
                "name": "add",
                "description": "Add two integers.",
                "parameters": {
                    "type": "object",
                    "properties": {"a": {"type": "integer"}, "b": {"type": "integer"}},
                    "required": ["a", "b"],
                },
            },
        }
    ]

    registry: ToolRegistry = {"add": add}
    initial_messages = [
        {"role": "system", "content": "Use the add tool for math."},
        {"role": "user", "content": "What is 2 + 3?"},
    ]

    result = run_agentic_chat(TextAI(), initial_messages, tools, registry)
    print(result.stop_reason, result.final_content)

Limitations:
- OpenAI-style tool calling only (function tools).
- Synchronous execution; no streaming.
- Forces Chat Completions (``use_responses=False``) so tool metadata is preserved.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Tuple

from ai_backend.api import TextAI

# A Python callable implementing a tool.
ToolFunc = Callable[..., Any]

# Mapping from tool name to callable.
ToolRegistry = Mapping[str, ToolFunc]


@dataclass
class AgentRunResult:
    """
    Result of running the agentic tool-calling loop.

    Attributes:
        messages: Final list of messages (original messages plus all assistant/tool messages).
        final_content: Final assistant natural-language content, if the loop produced one.
                       None if the loop ended due to a safeguard (e.g. max_steps).
        stop_reason: String describing why the loop ended. One of:
                     - "done": model produced a final answer (no tool calls).
                     - "max_steps": loop hit the configured max_steps limit.
                     - "repeated_tool_call": detected repeated identical tool calls.
        steps: Number of model steps executed (i.e. number of calls to TextAI.text_chat).
    """

    messages: List[Dict[str, Any]]
    final_content: Optional[str]
    stop_reason: str
    steps: int


def run_agentic_chat(
    text_ai: TextAI,
    messages: List[Dict[str, Any]],
    tools: Iterable[Dict[str, Any]],
    tool_registry: ToolRegistry,
    *,
    max_steps: int = 8,
    max_same_tool_calls: int = 3,
    temperature: float = 0.0,
) -> AgentRunResult:
    """
    Run a minimal tool-calling agent loop on top of TextAI and Chat Completions.

    This function:
    - Takes an initial messages list and a set of tool definitions.
    - Repeatedly calls TextAI.text_chat with tools enabled.
    - Executes any tool calls returned by the model using the provided tool_registry.
    - Feeds tool results back into the conversation as tool messages.
    - Stops when the model returns an assistant message without tool_calls,
      or when a safety limit (max_steps / max_same_tool_calls) is reached.

    Args:
        text_ai: Instance of ai_backend.TextAI used to call the underlying LLM.
        messages: List of OpenAI-style chat messages. This list is mutated in-place with
                  additional assistant and tool messages generated by the loop.
        tools: Iterable of tool definitions in the OpenAI Chat Completions format.
        tool_registry: Mapping from tool name (string) to a Python callable implementing
                       the tool. Callables must accept keyword arguments corresponding
                       to the tool's JSON object arguments.
        max_steps: Maximum number of model calls (iterations) allowed in this loop.
        max_same_tool_calls: Maximum number of consecutive identical tool calls
                             (same tool name and raw arguments) before the loop bails out
                             with stop_reason="repeated_tool_call".
        temperature: Temperature to pass to TextAI.text_chat.

    Returns:
        AgentRunResult describing the final messages, any final assistant content,
        and why the loop stopped.

    Notes:
        - This function uses the Chat Completions path and must ensure that
          TextAI.text_chat is called with use_responses=False so that tool_calls
          metadata is preserved.
        - The function supports multiple tool calls returned in a single model step.
    """

    tools_list = list(tools)
    last_signature: Optional[Tuple[str, str]] = None
    repeated_count = 0

    for step in range(1, max_steps + 1):
        choice = text_ai.text_chat(
            messages,
            tools=tools_list,
            tool_choice="auto",
            response_type="full",
            use_responses=False,
            temperature=temperature,
        )
        msg = choice.message
        tool_calls = getattr(msg, "tool_calls", None) or []

        if not tool_calls:
            final_content = msg.content or ""
            messages.append({"role": "assistant", "content": final_content})
            return AgentRunResult(
                messages=messages,
                final_content=final_content,
                stop_reason="done",
                steps=step,
            )

        assistant_msg: Dict[str, Any] = {
            "role": "assistant",
            "content": msg.content or "",
            "tool_calls": [],
        }
        tool_result_messages: List[Dict[str, Any]] = []

        for tc in tool_calls:
            tool_name = tc.function.name
            raw_args = tc.function.arguments or "{}"
            signature = (tool_name, raw_args)

            if signature == last_signature:
                repeated_count += 1
            else:
                last_signature = signature
                repeated_count = 1

            args: Optional[Dict[str, Any]] = None
            result: Any

            try:
                args = json.loads(raw_args)
                if not isinstance(args, dict):
                    raise ValueError("Tool arguments JSON must be an object")
            except Exception as exc:  # noqa: BLE001
                # Surface JSON parsing errors back to the model.
                result = {
                    "error": "invalid_tool_arguments",
                    "message": str(exc),
                    "raw_arguments": raw_args,
                }
            else:
                func = tool_registry.get(tool_name)
                if func is None:
                    result = {"error": "unknown_tool", "tool": tool_name, "arguments": args}
                else:
                    try:
                        result = func(**args)
                    except Exception as exc:  # noqa: BLE001
                        # Keep going even if tool execution fails.
                        result = {
                            "error": "tool_execution_error",
                            "tool": tool_name,
                            "message": str(exc),
                        }

            assistant_msg["tool_calls"].append(
                {
                    "id": tc.id,
                    "type": "function",
                    "function": {
                        "name": tool_name,
                        "arguments": raw_args,
                    },
                }
            )

            try:
                content = json.dumps(result)
            except TypeError:
                # Fallback for non-serializable results.
                content = json.dumps({"result": repr(result)})

            tool_result_messages.append(
                {
                    "role": "tool",
                    "tool_call_id": tc.id,
                    "name": tool_name,
                    "content": content,
                }
            )

        messages.append(assistant_msg)
        messages.extend(tool_result_messages)

        # Bail out if the model keeps repeating the same tool call.
        if repeated_count >= max_same_tool_calls:
            return AgentRunResult(
                messages=messages,
                final_content=None,
                stop_reason="repeated_tool_call",
                steps=step,
            )

    return AgentRunResult(
        messages=messages,
        final_content=None,
        stop_reason="max_steps",
        steps=max_steps,
    )
